/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Changelog': RouteRecordInfo<
      '/Changelog',
      '/Changelog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/DailyTasks': RouteRecordInfo<
      '/DailyTasks',
      '/DailyTasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Dashboard': RouteRecordInfo<
      '/Dashboard',
      '/Dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/GameFeatures': RouteRecordInfo<
      '/GameFeatures',
      '/GameFeatures',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/GameRoles': RouteRecordInfo<
      '/GameRoles',
      '/GameRoles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Home': RouteRecordInfo<
      '/Home',
      '/Home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Login': RouteRecordInfo<
      '/Login',
      '/Login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NotFound': RouteRecordInfo<
      '/NotFound',
      '/NotFound',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Profile': RouteRecordInfo<
      '/Profile',
      '/Profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Register': RouteRecordInfo<
      '/Register',
      '/Register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/TokenImport/': RouteRecordInfo<
      '/TokenImport/',
      '/TokenImport',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/TokenImport/bin': RouteRecordInfo<
      '/TokenImport/bin',
      '/TokenImport/bin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/TokenImport/manual': RouteRecordInfo<
      '/TokenImport/manual',
      '/TokenImport/manual',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/TokenImport/url': RouteRecordInfo<
      '/TokenImport/url',
      '/TokenImport/url',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/Changelog.vue': {
      routes:
        | '/Changelog'
      views:
        | never
    }
    'src/views/DailyTasks.vue': {
      routes:
        | '/DailyTasks'
      views:
        | never
    }
    'src/views/Dashboard.vue': {
      routes:
        | '/Dashboard'
      views:
        | never
    }
    'src/views/GameFeatures.vue': {
      routes:
        | '/GameFeatures'
      views:
        | never
    }
    'src/views/GameRoles.vue': {
      routes:
        | '/GameRoles'
      views:
        | never
    }
    'src/views/Home.vue': {
      routes:
        | '/Home'
      views:
        | never
    }
    'src/views/Login.vue': {
      routes:
        | '/Login'
      views:
        | never
    }
    'src/views/NotFound.vue': {
      routes:
        | '/NotFound'
      views:
        | never
    }
    'src/views/Profile.vue': {
      routes:
        | '/Profile'
      views:
        | never
    }
    'src/views/Register.vue': {
      routes:
        | '/Register'
      views:
        | never
    }
    'src/views/TokenImport/index.vue': {
      routes:
        | '/TokenImport/'
      views:
        | never
    }
    'src/views/TokenImport/bin.vue': {
      routes:
        | '/TokenImport/bin'
      views:
        | never
    }
    'src/views/TokenImport/manual.vue': {
      routes:
        | '/TokenImport/manual'
      views:
        | never
    }
    'src/views/TokenImport/url.vue': {
      routes:
        | '/TokenImport/url'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
